linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - ineffassign
    - govet
    - unused
    - misspell
    - bodyclose
    - errcheck
    - goimports
    - prealloc

issues:
  exlude-dirs:
    - vendor
